### ISSUE TITLE
Client credentials grant example

### ISSUE THREAD

**Issue by mayagithub87** [pedroetb/node-oauth2-server-example#1]
Hi Pedro, I'm new to all these stuff of NodeJs and node-oauth-server. I would love if you post an example like this but with client credentials grant, I did some research and saw that you must have the function getUserFromClient in the model required for auth, but I don't have any idea of how to do this, please Pedro could you help me?
Thanks a lot!

**Comment by pedroetb** [comment]
Hi maya, I'll try to do an example with that type of grant.

**Comment by pedroetb** [comment]
Done! I have expanded the original example to accept the `client_credentials` grant.

But before pushing it, I need to update the readme to mantain the example clarity. I'll update soon.

**Comment by mayagithub87** [comment]
Hola se que eres de España, yo soy de Cuba, un placer conocerte y gracias
ante todo por responder a mis inquietudes.
Antes de ver tu ejemplo del issue logre mas menos crear un ejemplo con el
tipo de grant client_credentials, lo que no me queda claro porque además
del cliente, tiene que existir un usuario, si con los ejemplos que he visto
de este tipo autenticacion solo lo emplea al cliente, por favor ver
https://stormpath.com/blog/talking-to-oauth2-services-with-nodejs.
Saludos
Maya

2017-01-13 19:06 GMT-05:00 Pedro Trujillo <notifications@github.com>:

**Comment by pedroetb** [comment]
Hola! Encantado ;)

As far as I can understand, the client_credentials grant doesn't require an user to work.

But in the node-oauth2-server implementation (in which my example is based) it seems to be required. I decided to return an auto-generated user for that client, but you can also return, for example, the same user for all clients using the client_credentials grant. Or maybe, only an empty json, I think (not tested, but probably).
