### ISSUE TITLE
expires_in missing

### ISSUE THREAD

**Issue by KimEbert42** [pedroetb/node-oauth2-server-example#10]
Looking at the Oauth specs aren't we supposed to be returning expires_in instead of accessTokenExpiresAt in our response?

**Comment by pedroetb** [comment]
Hi, I think using `expires_in` is recommended, but not mandatory (https://www.oauth.com/oauth2-servers/access-tokens/access-token-response/). But I agree with you in using the recommended property name.

This project is an example of usage of another project (https://github.com/oauthjs/node-oauth2-server), not under my control. Maybe you can ask for this there.

Thanks!
