### ISSUE TITLE
Missing new line in readme for password grant body

### ISSUE THREAD

**Issue by DKvarn** [pedroetb/node-oauth2-server-example#2]
In the readme for password grant under Body all paramters are in one line "grant_type=password&username=pedroetb&password=password", it should be three parameters:
grant_type=password
username=pedroetb
password=password

**Comment by DKvarn** [comment]
If you use curl it's right with onle line but I found it a bit confusing when not specifying the parameters on one row for each

**Comment by pedroetb** [comment]
Parameters notation is in one row to show the raw content that should be sent in request body.
Some REST clients allow users to define parameters one by one, but then they will be joined inline like that.

However, I put a note about parameters used in readme to clarify that.

Thanks.

**Comment by winju** [comment]
Hi, 
When i am using "grant_type=password&username=pedroetb&password=password" in Body.
with Authorization = Basic YXBwbGljYXRpb246c2VjcmV0   and 
Content-Type =application/x-www-form-urlencoded  in Headers.
I am getting an error  
{
    "code": 400,
    "error": "invalid_client",
    "error_description": "Missing parameters. \"username\" and \"password\" are required"
}
What might the thing that i am doing wrong here ?Help would be appreciated.
