### ISSUE TITLE
Refresh token example missing.

### ISSUE THREAD

**Issue by ShankzPatil** [pedroetb/node-oauth2-server-example#4]
Refresh token example missing in your model

**Comment by pedroetb** [comment]
I will add an example soon. Thanks!

**Comment by vsantoro** [comment]
Thanks. I got it working.

**Comment by pedroetb** [comment]
Hi @vsantoro, I suppose you got working grants types switching, asked at #5. I already answered there, but I'm glad to know you achieved it. Thanks!
