### ISSUE TITLE
Switch from Password to Client_Credentials grant type

### ISSUE THREAD

**Issue by vsantoro** [pedroetb/node-oauth2-server-example#5]
Password grant type is working great, how do I switch to client credentials grant type ? what needs to change ?

**Comment by pedroetb** [comment]
You can add or remove grants types at `app.js`, edit **grants** property in **oauthserver** instance:

```
app.oauth = oauthserver({
	model: require('./model.js'),
	grants: ['password', 'client_credentials'],
	debug: true
});
```

**Comment by vsantoro** [comment]
sorry, i meant to add this question in your other repo node-oauth2-server-mongo-example
