### ISSUE TITLE
validate token

### ISSUE THREAD

**Issue by vsantoro** [pedroetb/node-oauth2-server-example#6]
after generating client_credentials token how is the token validated ? what is the endpoint for this.

**Comment by pedroetb** [comment]
With *client_credentials* you get a token for the application, not for a user. When you get a new token with this grant type, you are identifying your request with a client id and a client secret. For many usage cases, that is enough.

For deeper explanation, refer to [oauth2 protocol documentation](https://oauth.net/2/grant-types/client-credentials/).
