### ISSUE TITLE
clarity regarding the flow

### ISSUE THREAD

**Issue by sundarkrish** [pedroetb/node-oauth2-server-example#7]
I am new to this oauth framework.Can you brief the flow of your model
Also I want to know who supplies the accessToken to saveAccessToken() function.

**Comment by sundarkrish** [comment]
getAccessToken() is called by the library to generate the JSON payload to be returned during localhost:3000/ ? 
We just have to write a logic to return the accessToken object from this method.And the library will do the internal calling ?

**Comment by pedroetb** [comment]
Hi,

`saveAccessToken()` is a method you must implement, and you know it will receive that parameters. This is determined by [node-oauth2-server](https://github.com/oauthjs/node-oauth2-server), my project is an example of usage.

`getAccessToken()` receives an access token from the user, and checks its validity (must has been generated previously). Also is called by the library, with a determined parameters.

Check [node-oauth2-server](https://github.com/oauthjs/node-oauth2-server) docs for further explanations.

Thanks.

**Comment by sundarkrish** [comment]
okay Thanks,I want some example on how to get refresh token along with access token.And also an example to use a refresh token got previously to get a new access token.
The grant type in the model is to define what all types the protocol supports.So,we can supply any one among those mentioned in the model,in our POST request payload .Am I correct ?

**Comment by pedroetb** [comment]
There is no example of refresh token grant type yet, but you can use it.

Add the desired grant types in server properties and then you can use them in your POST requests.

**Comment by sundarkrish** [comment]
Can we use multiple grant types.If yes,should it be separated by commas or by &.

**Comment by pedroetb** [comment]
No, you can send only one grant type by request. But you could request multiple access tokens with multiple requests, I suppose.
